### ISSUE TITLE
Unable to obtain USB-LEDS 

### ISSUE THREAD

**Issue by philipp1111** [TinyTitan/tinytitan.github.io#2]
Hello. 

I've got a problem concerning USB-LEDS, which are not that necessary, but are highly recommended in order to use this Tiny Titan. 

I searched for USB-LEDS like this in the internet, but everything I found is out of stock.. Is there any other opportunity to take possesion of these?

![image](https://cloud.githubusercontent.com/assets/20280779/16558279/c8188676-41e4-11e6-89e9-f1907b9ef330.png)

https://www.amazon.de/BlinkStick-Smart-USB-Controlled-LED-Pixel/dp/B00PLUXVXW

I also saw the instructions on this site http://tinytitan.github.io/downloads/TinyTitanBuildGuide.pdf but the link to find these LEDS is apparently not working.

**Comment by AdamSimpson** [comment]
The easiest solution, although a bit pricey, we've come across in the "blink1": https://blink1.thingm.com/buy/ .The link provides international purchasing options including DE/EU. Hope this helps!
